### ISSUE TITLE
parentcontrol not working

### ISSUE THREAD

**Issue by drspider** [elementary/switchboard-plug-parental-controls#55]
In Juno when I activate parent control for my kids and blocks some apps (appcenter, system settings etc) and when my kids login they can still use app center. system settings... without warning or admin login prompt

**Comment by gjsman** [comment]
@danrabbit I have the same issue. It is quite broken. 😢

**Comment by danrabbit** [comment]
So I dug back through commits and as far as I can tell the last working version is right before https://github.com/elementary/switchboard-plug-parental-controls/commit/ade6bb13616d51d16b4f6b48d0038253aa97c259

It looks like the switch to Meson build broke something here

**Comment by donadigo** [comment]
This should be fixed by #87.

**Comment by cyanit** [comment]
I just tried to set up a child account and it didn't work, is this still broken?
Would be nice to know how to get it working again :)

Cheers

**Comment by daninoregon79** [comment]
Still broken as of March 26 2020... I'd really like to get this working or I'll have to find something else for my kids.

**Comment by moremammal** [comment]
Primary importance to me and why I donated. Does not work.

**Comment by donadigo** [comment]
There have been some critical fixes merged recently. Look out for an update and please reopen if problems still persist.

**Comment by moremammal** [comment]
On 5.1.3 Hera, installed today. Is there an update coming or something I
should pull / download?

Thanks!
Joe

**Comment by donadigo** [comment]
You'll have to wait for the update. I don't think the fix was released yet.

**Comment by wleepang** [comment]
This is still not working with a fresh install of Hera and applied updates from AppCenter. When are the updates that addresses this issue planned to be released?
